course/urls.py
from django.urls import path
from .views import (CourseListView, CourseUpdateView, CourseDeleteView, CourseCreateView)

urlpatterns = [   
    path("", CourseListView.as_view(), name="course_list"),
    path("course/new/", CourseCreateView.as_view(), name="course_new"),
    path("course/<int:pk>/edit/", CourseUpdateView.as_view(), name="course_edit"),
    path("course/<int:pk>/delete/", CourseDeleteView.as_view(), name="course_delete")
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from apprentice.views import ApprenticeListado, ApprenticeDetalle, ApprenticeCrear, ApprenticeActualizar, ApprenticeEliminar

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("latearrival/" , include("latearrival.urls" )),
    path("course/" , include("course.urls" )),
    path('apprentice/', ApprenticeListado.as_view(template_name = "apprentice/index.html"), name='leer'),
    path('apprentice/detalle/<int:pk>', ApprenticeDetalle.as_view(template_name = "apprentice/detalles.html"), name='detalles'),
    path('apprentice/crear', ApprenticeCrear.as_view(template_name = "apprentice/crear.html"), name='crear'),
    path('apprentice/editar/<int:pk>', ApprenticeActualizar.as_view(template_name = "apprentice/actualizar.html"), name='actualizar'), 
    path('apprentice/eliminar/<int:pk>', ApprenticeEliminar.as_view(), name='eliminar'), 
]

latearrival/models.py
from django.db import models
from apprentice.models import Apprentice

# Create your models here.
class LateArrival(models.Model):
    #date_arrival = models.DateField(auto_now_add = True, auto_now=False, editable=False)
    date_arrival = models.DateField() 
    observations = models.CharField(null=True, blank=True, default='NINGUNA', max_length = 60)    
    document_apprentice = models.ForeignKey(
        Apprentice,
        on_delete = models.CASCADE,
    )
    
    def __str__(self):
        return self.document_apprentice.full_name +" "+ str(self.date_arrival)

templates/apprentice_list.html
{% extends "base.html" %}


{% block content %}


<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">Aprendices</span> 
    </div>
    <div class="card-body">

        <div class="d-grid gap-2 d-md-block">
            <button class="btn btn-primary">Nuevo</button>
        </div>

        <div class="row">
            <table id="table_apprentice" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">Documento</th>
                        <th scope="col" class="text-center">Nombre</th>
                        <th scope="col" class="text-center">Correo electrónico</th>
                        <th scope="col" class="text-center">Ficha</th>
                    </tr>
                </thead>
                <tbody>
                    {% for apprentice in apprentice_list %}
                        <tr class="text-center">
                            <th>{{ apprentice.document }}</th>
                            <td>{{ apprentice.full_name }}</td> 
                            <td>{{ apprentice.email }}</td> 
                            <td>{{ apprentice.id_course.id }}</td>                    
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        

    </div>
    
</div>
<br />

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <title>Arlet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />  
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
</head>

<div class="container">
    <header class="row">
        <img src="{% static 'img/banner.png' %}" class="img-fluid" alt="banner">
    </header>

    <p></p>

    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Arlet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" href="#">Home</a>
                        <a class="nav-link active" href="{% url 'late_arrival_list' %}">Llegadas tarde</a>
                        <a class="nav-link active" href="{% url 'leer' %}">Aprendices</a>
                        <a class="nav-link active" href="{% url 'course_list' %}">Fichas</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <br>

    <main>
        <div class="row">
            <div class="col-12">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %}>
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
        
        {% block content %}
        {% endblock content %}
    </main>

    <br>

    <footer class="row bg-primary text-center text-lg-start" >
        <div class="text-center p-3">            
            <span class="text-light">© 2022 Copyright: SENA 2022</span>
        </div>
    </footer>

</div>




<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>  
<!-- Bootstrap JavaScript Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    
<body>

templates/course_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="card col-md-6 offset-md-3 border-primary">
        <div class="card-header">
            <span class="font-weight-bold">Editar Ficha</span> 
        </div>
        <div class="card-body">
            <form action="" method="post" class="needs-validation" novalidate>{% csrf_token %}
                <div class="row">{{ form|crispy }}</div>
                <br>
                <div class="d-grid gap-2 d-md-block">
                    <button class="btn btn-success" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'course_list' %}">Cancelar</a>
                </div>                
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/course_list.html
{% extends "base.html" %}

{% block content %}


<div class="card border-primary">
    <div class="card-header">
        <span class="font-weight-bold">Fichas y Programas de formación</span>
    </div>
    <div class="card-body">
        <div class="d-grid gap-2 d-md-block">
            <a href="{% url 'course_new' %}" class="btn btn-primary">Nuevo</a>
        </div>

        <table id="table_course" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Ficha</th>
                    <th scope="col" class="text-center">Programa de formación</th>
                    <th scope="col" class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>

                {% for course in course_list %}                
                    <tr>
                        <th class="text-center">{{ course.id }}</th>
                        <td class="text-center">{{ course.career }}</td>
                        <td class="text-center">
                            <form method="POST" action="{% url 'course_delete' course.pk %}">{% csrf_token %}
                                <a href="{% url 'course_edit' course.pk %}" class="btn btn-info" role="button">Editar</a>
                                <button class="btn btn-danger" role="button" onclick="return eliminar();" type="submit">Eliminar</a>
                            </form>
                        </td>
                    </tr>                
                {% endfor %}

            </tbody>
        </table>

    </div>

</div>
<br />

<script type="text/javascript">
    function eliminar() {
        var x = confirm("¿Está seguro de que desea eliminar el registro?");
        if (x)
            return true;
        else
            return false;
    }


    $(document).ready(function () {
        $('#table_course').DataTable({
            "pageLength": 5,
            "lengthChange": false,
            "language": {
                "paginate": {
                    "previous": "Anterior",
                    "next": "Sgte"
                },
                "search": "Buscar:",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando 0 a 0 de 0 registros",
            }
        });
    });

</script>

{% endblock content %}

templates/course_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="card col-md-6 offset-md-3 border-primary">
        <div class="card-header">
            <span class="font-weight-bold">Crear Ficha</span> 
        </div>
        <div class="card-body">
            <form action="" method="post" class="needs-validation" novalidate>{% csrf_token %}
                <div class="row">{{ form|crispy }}</div>
                <br>
                <div class="d-grid gap-2 d-md-block">
                    <button class="btn btn-success" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'course_list' %}">Cancelar</a>
                </div>                
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/late_arrival_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="card col-md-6 offset-md-3 border-primary">
        <div class="card-header">
            <span class="font-weight-bold">Editar Registro de llegada tarde</span>
        </div>

        <div class="card-body">
            <form action="" method="post" class="needs-validation" novalidate>{% csrf_token %}
                <div class="row">{{ form|crispy }}</div>
                <br>
                <div class="d-grid gap-2 d-md-block">
                    <button class="btn btn-success" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'late_arrival_list' %}">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/late_arrival_list.html
{% extends "base.html" %}

{% block content %}

<div class="card border-primary">
    <div class="card-header">
        <span class="font-weight-bold">Registros de llegada tarde</span>
    </div>
    <div class="card-body">
        <div class="d-grid gap-2 d-md-block">
            <a href="{% url 'late_arrival_new' %}" class="btn btn-primary">Nuevo</a>
        </div>

        <hr>

        <div class="row">
            <div class="col-12">
                Ver/Ocultar columnas:
                <div class="btn-group" role="group">
                    <a class="toggle-vis btn btn-primary" data-bs-toggle="button" data-column="2">Aprendiz</a>
                    <a class="toggle-vis btn btn-primary" data-bs-toggle="button" data-column="3">Ficha</a>
                    <a class="toggle-vis btn btn-primary" data-bs-toggle="button" data-column="4">Observaciones</a>
                    <a class="toggle-vis btn btn-primary" data-bs-toggle="button" data-column="5">Acciones</a>
                </div>                
            </div>            
        </div>

        <table id="table_late" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Id</th>
                    <th scope="col" class="text-center">Fecha</th>
                    <th scope="col" class="text-center">Aprendiz</th>
                    <th scope="col" class="text-center">Ficha</th>
                    <th scope="col" class="text-center">Observaciones</th>
                    <th scope="col" class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>

                {% for latearrival in latearrival_list %}

                <tr>
                    <th class="text-center"><span id="id{{ latearrival.id }}">{{ latearrival.id }}</span></th>
                    <td class="text-center"><span id="date_arrival{{ latearrival.id }}">{{ latearrival.date_arrival }}</span></td>
                    <td class="text-center"><span id="document_apprentice{{ latearrival.id }}">{{ latearrival.document_apprentice.document }} - {{ latearrival.document_apprentice.full_name }}</span></td>
                    <td class="text-center"><span id="course{{ latearrival.id }}">{{ latearrival.document_apprentice.id_course.id }}</span></td>
                    <td class="text-center"><span id="observations{{ latearrival.id }}">{{ latearrival.observations }}</span></td>
                    <td class="text-center">
                        <form method="POST" action="{% url 'late_arrival_delete' latearrival.pk %}">{% csrf_token %}
                            <!-- <button id="btnVer" type="button" class="btn btn-primary ver" value="{{ latearrival.id }}">
                                Ver
                            </button> -->
                            <a href="{% url 'late_arrival_edit' latearrival.pk %}" class="btn btn-info"
                                role="button">Editar</a>
                            <button class="btn btn-danger" role="button" onclick="return eliminar();"
                                type="submit">Eliminar</a>
                        </form>
                    </td>
                </tr>
                <!-- Modal -->
                <!-- <div class="modal fade" id="exampleModal" tabindex="-1" data-bs-backdrop="static"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Detalle del registro</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p><strong>Id: </strong><span id="id_late"></span></p>
                                <p><strong>Fecha: </strong><span id="date_arrival"></span></p>
                                <p><strong>Aprendiz: </strong><span id="apprentice"></span></p>
                                <p><strong>Ficha:: </strong><span id="course"></span></p>
                                <p><strong>Observaciones: </strong><span id="observations"></span></p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                            </div>
                        </div>
                    </div>
                </div> -->
                <!-- Modal -->

                {% endfor %}

            </tbody>
        </table>

    </div>

</div>
<br />



<script type="text/javascript">
    function eliminar() {
        var x = confirm("¿Está seguro de que desea eliminar el registro?");
        if (x)
            return true;
        else
            return false;
    }

    

    /* $(document).ready(function () {
        $(document).on('click', '.ver', function () {
            var id = $(this).val();
            var id_late = $('#id' + id).text();
            var date_arrival = $('#date_arrival' + id).text();
            var document_apprentice = $('#document_apprentice' + id).text();
            var course = $('#course' + id).text();
            var observations = $('#observations' + id).text();
            //console.log(id_late);

            $('#exampleModal').modal('show');
            $('#id_late').text(id_late);
            $('#date_arrival').text(date_arrival);
            $('#apprentice').text(document_apprentice);
            $('#course').text(course);
            $('#observations').text(observations);
        });
    }); */

    $(document).ready(function () {
        var table = $('#table_late').DataTable({
            "pageLength": 5,
            "lengthChange": false,
            "language": {
                "paginate": {
                    "previous": "Anterior",
                    "next": "Sgte"
                },
                "search": "Buscar:",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando 0 a 0 de 0 registros",
            },
            "order": [[0, 'desc']],
        });

        $('a.toggle-vis').on('click', function (e) {
        e.preventDefault();
        var column = table.column($(this).attr('data-column')); 
        // Toggle the visibility
        column.visible(!column.visible());
    });
    });

</script>

{% endblock content %}

templates/late_arrival_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="card col-md-6 offset-md-3 border-primary">
        <div class="card-header">
            <span class="font-weight-bold">Registro de llegada tarde</span>
        </div>

        <div class="card-body">
            <form action="" method="post" class="needs-validation" novalidate>{% csrf_token %}
                <div class="row">{{ form|crispy }}</div>
                <br>
                <div class="d-grid gap-2 d-md-block">
                    <button class="btn btn-success" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'late_arrival_list' %}">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}